import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Loader2Icon, Globe, Eye, User, Calendar, ExternalLink } from 'lucide-react';
import api from '@/configs/axios';
import { toast } from 'sonner';

interface PublishedProject {
  id: string;
  name: string;
  initial_prompt: string;
  current_code: string;
  createdAt: string;
  user: {
    name: string;
  };
}

const Community = () => {
  const [loading, setLoading] = useState(true);
  const [projects, setProjects] = useState<PublishedProject[]>([]);
  const navigate = useNavigate();

  const fetchPublishedProjects = async () => {
    try {
      const { data } = await api.get('/api/project/published');
      setProjects(data.projects || []);
    } catch (error: any) {
      console.error('Error fetching community projects:', error);
      toast.error('Failed to load community projects');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchPublishedProjects();
  }, []);

  return (
    <div className="px-4 md:px-16 lg:px-24 xl:px-32 py-12 min-h-screen">
      {/* Header */}
      <div className="text-center mb-16">
        <div className="inline-flex items-center gap-2 bg-emerald-500/10 border border-emerald-500/20 rounded-full px-4 py-1.5 text-sm text-emerald-300 mb-6">
          <Globe className="size-3.5" />
          <span>Showcasing the best of Creatix Community</span>
        </div>
        <h1 className="text-4xl md:text-5xl font-bold text-white mb-4">
          Community <span className="bg-gradient-to-r from-emerald-400 to-cyan-400 bg-clip-text text-transparent">Showcase</span>
        </h1>
        <p className="text-gray-400 text-lg max-w-2xl mx-auto">
          Explore amazing websites generated by our community. Get inspired and start creating your own.
        </p>
      </div>

      {loading ? (
        <div className="flex items-center justify-center h-[50vh]">
          <Loader2Icon className="size-8 animate-spin text-emerald-400" />
        </div>
      ) : projects.length > 0 ? (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
          {projects.map((project) => (
            <div 
              key={project.id}
              className="group glass-card rounded-2xl overflow-hidden border border-white/10 hover:border-emerald-500/40 hover:shadow-[0_0_40px_rgba(16,185,129,0.15)] transition-all duration-500 flex flex-col"
            >
              {/* Preview Iframe Container */}
              <div className="relative h-48 bg-gray-950 overflow-hidden border-b border-white/5">
                <div className="absolute inset-0 z-10 bg-transparent group-hover:bg-black/20 transition-colors duration-300" />
                <iframe 
                  srcDoc={project.current_code}
                  className="w-[400%] h-[400%] origin-top-left pointer-events-none transition-transform duration-700 group-hover:scale-[1.02]"
                  style={{ transform: 'scale(0.25)' }}
                  sandbox="allow-scripts"
                />
                <div className="absolute bottom-4 right-4 z-20 opacity-0 group-hover:opacity-100 transition-opacity duration-300">
                   <button 
                    onClick={() => navigate(`/view/${project.id}`)}
                    className="p-2.5 bg-emerald-500 text-white rounded-xl shadow-xl active:scale-95 transition-all"
                   >
                     <Eye size={18} />
                   </button>
                </div>
              </div>

              {/* Info */}
              <div className="p-6 flex-1 flex flex-col">
                <div className="flex items-start justify-between mb-3">
                  <h3 className="text-xl font-bold text-white line-clamp-1 group-hover:text-emerald-400 transition-colors">
                    {project.name}
                  </h3>
                </div>
                <p className="text-gray-400 text-sm line-clamp-2 mb-6 flex-1 italic">
                  "{project.initial_prompt}"
                </p>

                {/* Meta */}
                <div className="flex items-center justify-between pt-4 border-t border-white/5 text-xs text-gray-500">
                  <div className="flex items-center gap-2">
                    <div className="size-6 rounded-full bg-emerald-500/20 flex items-center justify-center text-emerald-400">
                      <User size={12} />
                    </div>
                    <span>{project.user?.name || 'Anonymous'}</span>
                  </div>
                  <div className="flex items-center gap-1.5">
                    <Calendar size={12} />
                    <span>{new Date(project.createdAt).toLocaleDateString()}</span>
                  </div>
                </div>

                <button 
                  onClick={() => navigate(`/view/${project.id}`)}
                  className="mt-5 w-full py-2.5 bg-white/5 hover:bg-emerald-500/10 border border-white/10 hover:border-emerald-500/30 text-gray-300 hover:text-emerald-300 rounded-xl transition-all flex items-center justify-center gap-2 text-sm font-medium"
                >
                  View Full Site <ExternalLink size={14} />
                </button>
              </div>
            </div>
          ))}
        </div>
      ) : (
        <div className="text-center py-20 bg-white/5 rounded-3xl border border-white/10">
          <Globe className="size-12 text-gray-600 mx-auto mb-4" />
          <h2 className="text-2xl font-bold text-white mb-2">No projects published yet</h2>
          <p className="text-gray-500 max-w-sm mx-auto">
            Be the first to share your creation with the world! Go to your projects and toggle the publish switch.
          </p>
          <button 
            onClick={() => navigate('/projects')}
            className="mt-8 px-8 py-3 bg-emerald-600 hover:bg-emerald-700 text-white rounded-xl transition-all"
          >
            Go to My Projects
          </button>
        </div>
      )}
    </div>
  );
};

export default Community;
